[workspace]
members = [
    "crates/hl-common",
    "crates/hl-runner",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["HyperLiquidBench"]
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["clock"] }
clap = { version = "4.5", features = ["derive", "env"] }
csv = "1.3"
dotenvy = "0.15"
futures = "0.3"
hyperliquid_rust_sdk = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.8", features = ["macros"] }
thiserror = "1.0"
tokio = { version = "1.37", features = ["rt-multi-thread", "macros", "signal", "time"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1.7", features = ["serde", "v4"] }
ethers = "2.0"
